sudo: required
dist: trusty
language: scala

scala:
- 2.11.11
- 2.12.3

# see https://github.com/php-build/php-build/tree/master/share/php-build/definitions
env:
- JDK=oraclejdk8 PHP=5.6.31
- JDK=oraclejdk8 PHP=7.0.9
- JDK=oraclejdk8 PHP=7.1.7
- JDK=oraclejdk8 PHP=7.2.0beta3
- JDK=openjdk8 PHP=7.1.7
- JDK=openjdk8 PHP=7.2.0beta3

before_script:
- curl -L http://git.io/phpenv-installer | bash
- travis_wait 20 phpenv install $PHP
- phpenv global $PHP
- php --version
- jdk_switcher use $JDK

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
