language: scala

before_install:
- sudo add-apt-repository ppa:ondrej/php5-5.6 -y
- sudo apt-get update -qq
- sudo apt-get install -qq php5
- php --version

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test

scala:
- 2.11.7
- 2.10.5

jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
